services:

  auth-service:
    image: ujjwall1620/dineops-auth:latest
    container_name: dineops-auth
    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/dineops_auth
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    ports:
      - "8081:8081"